const mockDataGpt = [
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/nsV5Mfi9FAV4w8eDsdr7uqVswOk.jpg",
        genre_ids: [28, 12, 80, 53],
        id: 587412,
        original_language: "kn",
        original_title: "ಕೆ.ಜಿ.ಎಫ್: Chapter 2",
        overview:
          "The blood-soaked land of Kolar Gold Fields (KGF) has a new overlord now - Rocky, whose name strikes fear in the heart of his foes. His allies look up to Rocky as their Savior, the government sees him as a threat to law and order; enemies are clamoring for revenge and conspiring for his downfall. Bloodier battles and darker days await as Rocky continues on his quest for unchallenged supremacy.",
        popularity: 25.077,
        poster_path: "/khNVygolU0TxLIDWff5tQlAhZ23.jpg",
        release_date: "2022-04-14",
        title: "K.G.F: Chapter 2",
        video: false,
        vote_average: 7.401,
        vote_count: 152,
      },
      {
        adult: false,
        backdrop_path: "/4i1ofsSpfTuswHXcgPtXbZrSnoe.jpg",
        genre_ids: [53, 28, 12, 80],
        id: 564147,
        original_language: "kn",
        original_title: "ಕೆಜಿಎಫ್ ಅಧ್ಯಾಯ ೧",
        overview:
          "A period drama set in the 1970s, KGF follows the story of a fierce rebel who rises against the brutal oppression in Kolar Gold Fields and becomes the symbol of hope to legions of downtrodden people.",
        popularity: 17.033,
        poster_path: "/43ZvmTzIJ0tTzgLG8sDOfg9roLF.jpg",
        release_date: "2018-12-20",
        title: "K.G.F: Chapter 1",
        video: false,
        vote_average: 7.394,
        vote_count: 221,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 18, 53],
        id: 962640,
        original_language: "kn",
        original_title: "K.G.F: Chapter 3",
        overview: "",
        popularity: 6.583,
        poster_path: "/ex2zyM6LVd31h9TlAi9RaR7QARK.jpg",
        release_date: "",
        title: "K.G.F: Chapter 3",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
    ],
    total_pages: 1,
    total_results: 3,
  },
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/mIisDBJVAsugwReRoeAuWIDnc9S.jpg",
        genre_ids: [35, 80],
        id: 21614,
        original_language: "hi",
        original_title: "Hera Pheri",
        overview:
          "Three unemployed men find the answer to all their money problems when they receive a call from a kidnapper. However, things do not go as planned.",
        popularity: 7.885,
        poster_path: "/kdgazQ9Beh6IzFCGtjHb93w0KXk.jpg",
        release_date: "2000-03-31",
        title: "Hera Pheri",
        video: false,
        vote_average: 6.958,
        vote_count: 253,
      },
      {
        adult: false,
        backdrop_path: "/vr4fskAEI91XoBNMxEiW8Tx3Q6g.jpg",
        genre_ids: [28, 35, 18],
        id: 170645,
        original_language: "hi",
        original_title: "Hera Pheri",
        overview:
          "Two con men, Vijay and Ajay, manage to hoodwink a number of wealthy people as well as Police Commissioner Khanna. Their lives undergo many changes, after a caper at a casino, where Vijay is recognized by a gangster named P.K., who decides to separate the two friends by claiming that Ajay is his long-lost son; insinuating that Vijay has not been completely forthright with Ajay; and implicating him in the murder of a male named Mac. Written by rAjOo (gunwanti@hotmail.com)",
        popularity: 3.416,
        poster_path: "/hUlekD8DKi7GBTqy5HIrVovnU8i.jpg",
        release_date: "1976-10-01",
        title: "Hera Pheri",
        video: false,
        vote_average: 5.9,
        vote_count: 8,
      },
      {
        adult: false,
        backdrop_path: "/802ronXWzXTOlue05ZBTZqSTSFH.jpg",
        genre_ids: [35],
        id: 20359,
        original_language: "hi",
        original_title: "Phir Hera Pheri",
        overview:
          "Raju,  Shyam and Baburao are living happily after having risen from rags to riches. However, they lose it all after falling victim to a chit fund scam due to their greed for more money. Soon, they find themselves in new mess and encounter eccentric and dangerous characters in their quest for a shortcut to riches again.",
        popularity: 13.702,
        poster_path: "/c1Mvyd983ZyrU5Vf2aKEe6WncSq.jpg",
        release_date: "2006-06-09",
        title: "Phir Hera Pheri",
        video: false,
        vote_average: 6.6,
        vote_count: 119,
      },
      {
        adult: false,
        backdrop_path: "/thcoTAEBIk9EiDscqAOV8uZCHVl.jpg",
        genre_ids: [18, 35],
        id: 682856,
        original_language: "pa",
        original_title: "ਤੇਰੀਆਂ ਮੇਰੀਆਂ ਹੇਰਾ ਫੇਰੀਆਂ",
        overview:
          "Lucky is a young taxi driver whose dream of moving to the UK is thwarted by financial constraints. When he falls for Paali, whose father proposes a fake marriage to facilitate her UK immigration, Lucky agrees, hoping to win her love",
        popularity: 1.105,
        poster_path: "/oZBIvd8aBFV8CnSQGwEIL3QDTIu.jpg",
        release_date: "2024-06-21",
        title: "Teriya Meriya Hera Pheriyan",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [35],
        id: 998131,
        original_language: "bn",
        original_title: "হেরা ফেরী",
        overview:
          "'Hera Pheri' is the story of a con man Ronnie and a con woman Bonny who cheat people for money. But it's gradually revealed that Bonny wants money to build a mental asylum where mentally unstable people like her mother can be treated. On a fateful night years back criminal named Bhagare Shashthi attacked Bata Krishna's jewelry shop and on their way back they had killed Bonny's father and charged young Ronnie of the murder. After the truth is revealed Bonny and Ronnie start working together for money. One day Bata Krishna receives a ransom call from Sashti meant for Haladhar Manna. Signal, Ronnie's aide decides to pose as kidnappers and call Manna. They demand double the amount demanded by kidnappers. After a lot of complications the child is rescued, Ronnie gets the money and Sashti gets killed.",
        popularity: 0.403,
        poster_path: "/eS2phxS0NMw1QhiXe39TajANnGl.jpg",
        release_date: "2016-02-04",
        title: "Hera Pheri",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [35],
        id: 393429,
        original_language: "hi",
        original_title: "Hera Pheri 3",
        overview: "",
        popularity: 2.137,
        poster_path: null,
        release_date: "",
        title: "Hera Pheri 3",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/mF52lhsQMXQmZIId6CqQo2FJfux.jpg",
        genre_ids: [35, 28],
        id: 38628,
        original_language: "te",
        original_title: "ఢీ",
        overview:
          "Babloo (Vishnu) likes to have fun and is always getting in trouble so his father (Chandramohan) gets him a job with Shanker Goud (Srihari). Shanker Goud and Bhallu are rivals and Bhallu is determined to kill Shanker Goud's sister Pooja (Genelia D'Souza). Babloo falls in love with Pooja but Shanker is planning an arranged marriage for her with Ajay (Akash) so Babloo and Pooja elope. The rest of the story is about how Babloo saves Pooja from Bhallu.",
        popularity: 2.629,
        poster_path: "/pi39lj9U806VIj6EHUScSTpjGLt.jpg",
        release_date: "2007-04-13",
        title: "Dhee",
        video: false,
        vote_average: 6.3,
        vote_count: 9,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [35, 18, 10751],
        id: 171384,
        original_language: "te",
        original_title: "దేనికైనా రేడీ",
        overview:
          "Veera Narasimha Naidu (Prabhu) is a faction leader in Kurnool who raised his sister Saraswati (Seetha) with love and Affection to make her forget the loss of their Mother. During the marriage time, she eloped with Basha (Suman), whom she loved which led the death of Narasimha Naidu's Father. Thus enraged Narasimha Naidu cuts the leg of Basha which created a rift between the two families. On a case to win the property belonging to Saraswati, Basha wins the case on Narasimha Naidu after a long gap of 25 years. Seeing the sorrow of Saraswati, her son Sulaiman (Vishnu Manchu) vows to unite the two families and waits for a situation.",
        popularity: 1.765,
        poster_path: "/bdrcCzcNUzRiNEE7uRXTzzCoG5s.jpg",
        release_date: "2012-10-23",
        title: "Dhenikaina Ready",
        video: false,
        vote_average: 4.5,
        vote_count: 6,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [35, 10751, 18],
        id: 253047,
        original_language: "te",
        original_title: "పాండవులు పాండవులు తుమ్మెద",
        overview:
          "When Naidu confronts his son's rival group to end their squabbles, he encounters their mother Satya, his long lost love, separated by the twist of fate. As Honey learns the secret between Naidu and Satya, she is kidnapped by her father's arch rival Suyodhana Goud, who sees an opportunity to unwillingly ensnare her into a marriage with his son. Although these unfortunate turn of events bring Naidu, Satya and their sons together, they must devise a clever escape plan for Honey in this comedy-action journey.",
        popularity: 0.596,
        poster_path: "/nQxRb9HOnVAlqTuBkGcxq8W4sa1.jpg",
        release_date: "2014-01-31",
        title: "Paandavulu Paandavulu Thummeda",
        video: false,
        vote_average: 6,
        vote_count: 3,
      },
    ],
    total_pages: 1,
    total_results: 9,
  },
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/9c4soJ1f1IPAyoCj0CDwKNThsBV.jpg",
        genre_ids: [35],
        id: 19637,
        original_language: "hi",
        original_title: "चुप चुप के",
        overview:
          "After surviving a suicide attempt in which his family and fellow villagers believe he drowned, a debt-ridden man decides to start his life afresh in another village. He pretends to be mute and starts working for a rich man where he falls in love with his mute daughter.",
        popularity: 10.052,
        poster_path: "/daXoADAtEPis5bBvSrXVWfRa77X.jpg",
        release_date: "2006-06-09",
        title: "Chup Chup Ke",
        video: false,
        vote_average: 6.2,
        vote_count: 88,
      },
    ],
    total_pages: 1,
    total_results: 1,
  },
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/keC82cQ8q0ZHthrbvzWq04kGnbv.jpg",
        genre_ids: [80, 28, 53],
        id: 857598,
        original_language: "te",
        original_title: "పుష్పా 2 - The Rule",
        overview:
          "Pushpa struggles to sustain his sandalwood smuggling business in the face of tough opposition from the police, led by Shekhawat.",
        popularity: 168.57,
        poster_path: "/1T21FblunT0y8fz7YaW8JMYgUKm.jpg",
        release_date: "2024-12-04",
        title: "Pushpa 2 - The Rule",
        video: false,
        vote_average: 7.3,
        vote_count: 23,
      },
      {
        adult: false,
        backdrop_path: "/2f9YnS7JKrIqBv7dMQG8sRS2aJv.jpg",
        genre_ids: [28, 18, 53],
        id: 690957,
        original_language: "te",
        original_title: "పుష్పా - The Rise",
        overview:
          "Pushpa Raj is a coolie who rises in the world of red sandalwood smuggling. Along the way, he doesn’t shy from making an enemy or two.",
        popularity: 46.008,
        poster_path: "/r1yAzVQNbCbPTbB3GZFour9Qr0t.jpg",
        release_date: "2021-12-16",
        title: "Pushpa: The Rise",
        video: false,
        vote_average: 7.004,
        vote_count: 130,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 35, 14],
        id: 1258916,
        original_language: "ml",
        original_title: "പുഷ്പക വിമാനം",
        overview:
          "After covering up a tragic incident, a man faces a race against time to prevent the truth being exposed.",
        popularity: 3.289,
        poster_path: "/iEfFplXZj4ofZlI1dhPQsBTErUH.jpg",
        release_date: "2024-10-04",
        title: "Pushpaka Vimanam",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/vC1muIEfoOhMORQ7ld4hEe13WlS.jpg",
        genre_ids: [35, 10751, 18],
        id: 463677,
        original_language: "kn",
        original_title: "Pushpaka Vimana",
        overview:
          "A mentally-challenged father lives in his idyllic world with his daughter, both of them crazy about planes. In his quest to get his daughter that toy plane that she yearns for, he ends up in jail wrongly accused of a crime he doesn't commit. What follows is a bittersweet tale of a father and daughter trying to be together...",
        popularity: 1.012,
        poster_path: "/taMRVzDyXoS2IVjhLs2Vk6JKbRm.jpg",
        release_date: "2017-01-06",
        title: "Pushpaka Vimana",
        video: false,
        vote_average: 8.7,
        vote_count: 3,
      },
      {
        adult: false,
        backdrop_path: "/pXHZR1QssA19PDUlyweoAxNujbQ.jpg",
        genre_ids: [35, 18, 10749],
        id: 36810,
        original_language: "kn",
        original_title: "ಪುಷ್ಪಕ ವಿಮಾನ",
        overview:
          "An unemployed man, who dreams of living it large, finds a rich man drunk and lying in the sewer. Things take a turn when he imprisons him and takes his identity to get a taste of his lifestyle.",
        popularity: 4.244,
        poster_path: "/cYr2HQHSKYGDpMlBhL6e79Dbg6H.jpg",
        release_date: "1987-11-17",
        title: "Pushpaka Vimana",
        video: false,
        vote_average: 7.1,
        vote_count: 28,
      },
      {
        adult: false,
        backdrop_path: "/6ejbHCy0hH0fvMNLEHmaINjQsaP.jpg",
        genre_ids: [10749, 18, 12, 35],
        id: 445959,
        original_language: "ta",
        original_title: "பன்னீர் புஷ்பங்கள்",
        overview:
          "Two high school students receive ample support from one of their teachers to fall in love with each other. But problems arise when their parents come to know about their relationship.",
        popularity: 0.363,
        poster_path: "/tkqareX5pxgC1bUkYxMbbsGTiMi.jpg",
        release_date: "1981-07-03",
        title: "Panneer Pushpangal",
        video: false,
        vote_average: 8,
        vote_count: 1,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 306346,
        original_language: "ml",
        original_title: "അഗ്നിപുഷ്പം",
        overview: "",
        popularity: 0.844,
        poster_path: "/8nfJi7Q7QxnutZck4HJW8UJysm.jpg",
        release_date: "1976-01-09",
        title: "Agni Pushpam",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/i5rbYSbN7kvhOnr0u2pxOHusMrv.jpg",
        genre_ids: [10751, 10749, 35],
        id: 878470,
        original_language: "te",
        original_title: "పుష్పక విమానం",
        overview:
          "Sundar is a typical middle-class guy, working as a government teacher. He has to come up against a strangely unusual situation after his wife Meenakshi elopes with someone else soon after their marriage and to now convince the entire world that everything is alright.",
        popularity: 1.597,
        poster_path: "/jd5vrm1WnNJ1ifTqajKGEJexzzI.jpg",
        release_date: "2021-11-12",
        title: "Pushpaka Vimanam",
        video: false,
        vote_average: 6,
        vote_count: 2,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 80, 53],
        id: 1300535,
        original_language: "te",
        original_title: "పుష్ప 3 - The Rampage",
        overview:
          "The third installment in the Pushpa film series. Premise TBA.",
        popularity: 0.001,
        poster_path: "/8qA9YwgNABjSFhZKXBzCW3YSJ8F.jpg",
        release_date: "",
        title: "Pushpa 3 - The Rampage",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 66328,
        original_language: "ta",
        original_title: "Aaru Pushpangal",
        overview:
          "Aarupushpangal is a Tamil film is directed by K.M.Balakrishnan.",
        popularity: 1,
        poster_path: null,
        release_date: "1977-11-10",
        title: "Aaru Pushpangal",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/kTYeO5HFRhl0gNd3y6tEg1MZChc.jpg",
        genre_ids: [35],
        id: 1396798,
        original_language: "te",
        original_title: "Pushpak Vimaan",
        overview:
          "A hopeful romantic, Ishaan plans a star-crossed proposal guided by his horoscope. But will fate and a series of hilarious mishaps let love bloom at exactly 6:30 PM?",
        popularity: 0.806,
        poster_path: "/1YuKLKmascPRCXQVcpVcfQbVwfn.jpg",
        release_date: "2024-10-27",
        title: "Pushpak Vimaan",
        video: true,
        vote_average: 9,
        vote_count: 1,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [99],
        id: 1141210,
        original_language: "en",
        original_title: "POD Pushpavalli",
        overview:
          "Sumukhi Suresh forces Debbie Rao to speak in front of the camera about the making of Pushpavalli Season 1 and 2.",
        popularity: 0.442,
        poster_path: "/kwmjFXSxs1RL8YWtzLHYtQV7om8.jpg",
        release_date: "2020-04-14",
        title: "POD Pushpavalli",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/d1CYMhiHcPs7P2x5WHsNCw2QSo6.jpg",
        genre_ids: [35, 18, 53],
        id: 682838,
        original_language: "hi",
        original_title: "O Pushpa I Hate Tears",
        overview:
          "You always fall in love with those whom you want to be the part of your life. This is the only truth and only condition. When Aditya fallen in love with Pushpa, she thought that he only loves her. But she gets traumatized when she came to know that Aditya was in love with her only to get her money. He only wants money not Pushpa. Aditya wants Pushpa out of his way, so he takes the help of Shyam. But Shyam smartly get Pushpa in love with him and also get a hold on her. Shyam is so clever that its impossible for Aditya to remove Shyam from Pushpa’s life and her money. Now Aditya is helpless and feels like he lost Pushpa and her money as well. What Aditya will do now?",
        popularity: 1,
        poster_path: "/sRAlQCKkkalbo2Heg2So9GW0EvT.jpg",
        release_date: "2020-02-28",
        title: "O Pushpa I Hate Tears",
        video: false,
        vote_average: 10,
        vote_count: 1,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [10749, 18],
        id: 1116910,
        original_language: "bn",
        original_title: "Pushpadhanu",
        overview:
          "The movie Pushpadhanu is based on human relations and sentiments.",
        popularity: 0.823,
        poster_path: "/nxvu3EVYxDcimQhKqWuAO8jdU6F.jpg",
        release_date: "1959-06-25",
        title: "Pushpadhanu",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [],
        id: 1145143,
        original_language: "ta",
        original_title: "Paarijaatha Pushpaha Ragam",
        overview:
          "Director  Raja Sandow P.K.  Stars  R. Nagendra RaoK.T. RukminiLeela",
        popularity: 0.001,
        poster_path: null,
        release_date: "1932-01-01",
        title: "Paarijaatha Pushpaha Ragam",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [],
        id: 304740,
        original_language: "en",
        original_title: "Raktha Pushpam",
        overview: "Film with the music of K. J. Yesudas.",
        popularity: 0.001,
        poster_path: null,
        release_date: "",
        title: "Raktha Pushpam",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
    ],
    total_pages: 1,
    total_results: 16,
  },
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/5qjbu7po6eqLNd4kUPAyIpFRwQK.jpg",
        genre_ids: [18, 10751, 35, 28],
        id: 360814,
        original_language: "hi",
        original_title: "दंगल",
        overview:
          "Dangal is an extraordinary true story based on the life of Mahavir Singh and his two daughters, Geeta and Babita Phogat. The film traces the inspirational journey of a father who trains his daughters to become world class wrestlers.",
        popularity: 19.914,
        poster_path: "/lHd3W8E5aKoki9pDP7tN7yEh3c0.jpg",
        release_date: "2016-12-21",
        title: "Dangal",
        video: false,
        vote_average: 7.9,
        vote_count: 981,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 936232,
        original_language: "tl",
        original_title: "Magkano Ang Iyong Dangal?",
        overview:
          "When love dies and infidelity sets in, what happens to a young couple who vow to love each other forever?",
        popularity: 0.64,
        poster_path: "/k0VXO3FlaZuC6BliXNjs9eFawfm.jpg",
        release_date: "1988-12-25",
        title: "Magkano Ang Iyong Dangal?",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 508919,
        original_language: "tl",
        original_title: "Kapirasong Dangal",
        overview: "",
        popularity: 1.631,
        poster_path: "/1NVvjdzDfyzqMIIzJVbAphVxUoY.jpg",
        release_date: "1986-08-14",
        title: "Kapirasong Dangal",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 1053686,
        original_language: "tl",
        original_title: "Sugat sa Dangal",
        overview: "",
        popularity: 2.223,
        poster_path: "/gJP0rhakCwHELjnaWbwW70MA6YL.jpg",
        release_date: "1985-02-28",
        title: "Sugat sa Dangal",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/VxBK9ahhXZH5cd81xvWAV6JJVs.jpg",
        genre_ids: [],
        id: 829952,
        original_language: "en",
        original_title: "One Championship: Dangal",
        overview:
          "In the main event, longtime ONE Heavyweight World Champion Brandon Vera defends his belt against surging contender Arjan Bhullar, who is on a historic quest to become the first-ever Indian World Champion in mixed martial arts.  Also on the stacked card, Indian wrestling superstar Ritu Phogat faces veteran striker Bi Nguyen in a classic clash of styles.",
        popularity: 0.055,
        poster_path: null,
        release_date: "2021-05-13",
        title: "One Championship: Dangal",
        video: true,
        vote_average: 6,
        vote_count: 1,
      },
      {
        adult: false,
        backdrop_path: "/ba5Nw6E27IesLeuBCf9l1nFcJSo.jpg",
        genre_ids: [35],
        id: 16889,
        original_language: "en",
        original_title: "Revenge of the Nerds II: Nerds in Paradise",
        overview:
          "The members of the Lambda Lambda Lambda fraternity travel to Fort Lauderdale for a fraternity conference. They'll have to beat off the attacks of their rival frat, the Alphas, if they want to maintain their self-respect -- and, of course, if they want to get anywhere with the pretty girls!",
        popularity: 20.122,
        poster_path: "/cza5sS7AzexM4rLQSvfGzGX8a3N.jpg",
        release_date: "1987-07-10",
        title: "Revenge of the Nerds II: Nerds in Paradise",
        video: false,
        vote_average: 5.6,
        vote_count: 269,
      },
    ],
    total_pages: 1,
    total_results: 6,
  },
];

export const mockMovieNames = [
  "K.G.F: Chapter 2",
  "Hera Pheri",
  "Chup Chup Ke",
  "Pushpa 2 - The Rule",
  "Dangal",
];

export default mockDataGpt;
